Travis refacto
aya-experience/aya-day-team pull request #11
Opened 2019-01-29 09:26 UTC by christopherkade

Refactored Travis CI/CD process
- Cleaner
- Divided into stages

Fixed client-side linting errors

2019-01-29 14:41 UTC, FBerthelot commented on client/src/components/Desktop/Desktop.test.js
> +/* eslint-disable no-global-assign */
pk ?

2019-01-29 14:41 UTC, FBerthelot commented on client/src/components/Desktop/QR/QR.test.js
> +import * as enzyme from 'enzyme';
préfère le déstructuring ici.

Le `import * as toto from ...` n'est pas une bonne pratique en général

2019-01-29 14:41 UTC, FBerthelot commented on client/src/components/Desktop/QR/QR.test.js
> +import Adapter from 'enzyme-adapter-react-16';
Tu n'en as pas besoin ici

2019-01-29 14:41 UTC, FBerthelot commented on client/src/components/Mobile/Mobile.js
> +/* eslint-disable react/no-unused-state, no-undef */
pk ?

2019-01-29 14:41 UTC, FBerthelot commented on client/src/components/Mobile/Mobile.test.js
> +/* eslint-disable no-global-assign */
pk ?

2019-01-29 14:41 UTC, FBerthelot commented on client/src/components/utils/webrtc.js
> +/* eslint-disable no-undef, no-console */
préfère un ignore-line devant chaque console ;)

2019-01-29 14:41 UTC, FBerthelot commented on client/src/registerServiceWorker.js
> +/* eslint-disable */
feignasse

2019-01-29 14:43 UTC, christopherkade commented on client/src/components/Desktop/Desktop.test.js
> +/* eslint-disable no-global-assign */
Sinon je peux pas mocker `console` via 
```
console = {
  ...console,
  log: jest.fn(),
  error: jest.fn()
};
```

2019-01-29 14:44 UTC, christopherkade commented on client/src/components/Desktop/QR/QR.test.js
> +import * as enzyme from 'enzyme';
Yes, je ne sais même pas pourquoi j'ai laissé ça ici, c'est moche 😞

2019-01-29 14:45 UTC, christopherkade commented on client/src/components/Desktop/QR/QR.test.js
> +import Adapter from 'enzyme-adapter-react-16';
Pas besoin de quoi spécifiquement? De l'`Adapter`?

2019-01-29 14:46 UTC, christopherkade commented on client/src/components/Mobile/Mobile.test.js
> +/* eslint-disable no-global-assign */
Même réponse qu'ici: https://github.com/aya-experience/aya-day-team/pull/11#discussion_r251861360

2019-01-29 14:49 UTC, christopherkade commented on client/src/components/utils/webrtc.js
> +/* eslint-disable no-undef, no-console */
Même si il y a une 10/20 console logs actifs sur un projet? Est-ce que ça signifie que j'abuse trop des console log de façon générale?

2019-01-29 14:51 UTC, christopherkade commented on client/src/components/Mobile/Mobile.js
> +/* eslint-disable react/no-unused-state, no-undef */
`no-undef` ==> car eslint veut que je défini `EventSource` alors que c'est natif au navigateurs.
`no-unused-state` ==> car pour le moment je n'utilise pas le state `webRTC` qui devrait être utilisé par la suite

2019-02-04 10:42 UTC, FBerthelot requested changes

2019-02-04 10:42 UTC, FBerthelot commented on client/src/components/Desktop/Desktop.js
> +/* eslint-disable no-undef */
💩

2019-02-04 11:14 UTC, merged