QR Code generation
aya-experience/aya-day-team pull request #5
Opened 2018-12-04 13:53 UTC by christopherkade

Once a key is received from the server (via SSE stream): generate a QR code with a URL & key as parameter in order to give access to the website to the mobile client

2018-12-04 14:22 UTC, christopherkade commented on client/src/components/Desktop/Desktop.js
> +      this.createQRCode("http://192.168.1.111:3000", e.data, 10, "L");
💩

2018-12-04 14:22 UTC, christopherkade commented on client/src/components/Desktop/Desktop.js
> +      console.log("---- MESSAGE: ", e);
💩 (console.log)

2018-12-12 09:52 UTC, FBerthelot commented on client/src/components/Desktop/Desktop.js
> +    document.getElementsByClassName("qr")[0].innerHTML = qr.createImgTag();
Faire ça dans un coposant (ne jamais utiliser directement l'API DOM dans un framework JS)

2018-12-12 09:52 UTC, FBerthelot commented on client/src/components/Desktop/Desktop.js
> +        process.env.REACT_APP_ENV === "dev"
TODO avoir une meilleur gestion des variable d'env

2018-12-12 09:52 UTC, FBerthelot commented on client/src/components/Mobile/Mobile.js
> +    let elements = document.getElementsByClassName("focused");
Idem, tu accède au dom directement

2018-12-12 09:52 UTC, FBerthelot commented on client/src/components/Mobile/Mobile.js
> +    /* this.socket.emit("do-stuff-on-browser", { name }); */
💩

2018-12-12 09:52 UTC, FBerthelot commented on client/src/components/Mobile/Mobile.test.js
> +  it("renders the component without crashing", () => {
finir les tests (copier/coller les tests du desktop)

2018-12-12 09:52 UTC, FBerthelot commented on server/redis.js
> +    const PORT = '6379';
met un TODO, handle config

2018-12-12 09:52 UTC, FBerthelot commented on server/tests/methods.test.js
> +  it('should generate a random desktop key', async () => {
```suggestion
  it('should generate a random desktop key', () => {
```

2018-12-12 09:52 UTC, FBerthelot commented on server/tests/methods.test.js
> +  it('should generate a random mobile key', async () => {
```suggestion
  it('should generate a random mobile key', () => {
```

2018-12-12 09:52 UTC, FBerthelot commented on server/tests/methods.test.js
> +    const key = utils.generateKey(false);
Warning, les tests ne doivent pas passer

2018-12-12 09:52 UTC, FBerthelot commented on server/tests/routes.test.js
> +  it('should respond with a valid status', async () => {
```suggestion
  it('should respond with a valid status', () => {
```

2018-12-12 09:52 UTC, FBerthelot commented on server/tests/routes.test.js
> +  it('should respond with a valid response type', async () => {
```suggestion
  it('should respond with a valid response type', () => {
```

2018-12-12 09:52 UTC, FBerthelot commented on server/tests/routes.test.js
> +  it('should respond with a valid header', async () => {
```suggestion
  it('should respond with a valid header',  () => {
```

2018-12-12 09:52 UTC, FBerthelot commented on server/tests/routes.test.js
> +  it('should return a valid response type and random key', async () => {
```suggestion
  it('should return a valid response type and random key', () => {
```

2018-12-12 13:22 UTC, christopherkade commented on client/src/components/Mobile/Mobile.js
> +    let elements = document.getElementsByClassName("focused");
Ça sera changé dans la prochaine PR qui s'occupera du Mobile 😀

2018-12-12 13:23 UTC, christopherkade commented on client/src/components/Mobile/Mobile.test.js
> +  it("renders the component without crashing", () => {
Idem, sera fait dans la prochaine PR

2018-12-13 09:30 UTC, FBerthelot requested changes

2018-12-13 09:30 UTC, FBerthelot commented on client/src/components/Mobile/Mobile.js
> +    let elements = document.getElementsByClassName("focused");
Met un TODO dans ce cas !

2018-12-13 09:30 UTC, FBerthelot commented on client/src/components/Mobile/Mobile.test.js
> +  it("renders the component without crashing", () => {
Si tu fais ça dans une autre PR, met un TODO !

2018-12-13 09:30 UTC, FBerthelot commented on server/redis.js
> +    const PORT = '6379';
Pas fait ici

2018-12-13 09:30 UTC, FBerthelot commented on server/tests/routes.test.js
> +  it('should respond with a valid response type', async () => {
pas fait

2018-12-13 09:30 UTC, FBerthelot commented on server/tests/routes.test.js
> +  it('should respond with a valid status', async () => {
pas fait

2018-12-13 09:30 UTC, FBerthelot commented on server/tests/routes.test.js
> +  it('should respond with a valid header', async () => {
pas fait

2018-12-13 09:30 UTC, FBerthelot commented on server/tests/routes.test.js
> +  it('should return a valid response type and random key', async () => {
pas fait

2018-12-13 09:51 UTC, FBerthelot commented on client/src/components/Desktop/Desktop.js
> +      // TODO: avoir une meilleur gestion des variable d'env
le TODO n'a plus lieu d'être

2018-12-13 15:13 UTC, FBerthelot commented on server/routes.spec.js
> +// TODO: Fix route tests
?

2019-01-09 13:01 UTC, merged